version: '3.9'

services:
    mysql-db:
        container_name: 'mysql-db' 
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'rootPassword*01'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'redis_demo'
            MYSQL_USER: 'awesomeuser'
            MYSQL_PASSWORD: 'userpassword*01'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'msyqlvol:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - demo
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p rootPassword*01'
            retries: 3
            timeout: 5s
    redis:
        container_name: 'redis-db'
        image: 'redis'
        ports:
            - '6379:6379'
        volumes:
            - 'redisvol:/data'
        #     - './docker/redis/redis.conf:/usr/local/etc/redis/redis.conf'
        # entrypoint: 'redis-server /usr/local/etc/redis/redis.conf'
        networks:
            - demo
volumes:
    msyqlvol:
        driver: local
    redisvol:
        driver: local
networks:
    demo:
        name: demo